### ISSUE TITLE
Trying to connect to a database without password

### ISSUE THREAD

**Issue by Lloople** [vapor/mysql-driver#195]
I have no password for the root user in my development machine, but I'm unable to run the migrations because of the following error:

```
➜  users-api git:(master) ✗ vapor run migrate
Migrate Command: Prepare
[ ERROR ] MySQL error: Server error: Access denied for user 'root'@'localhost' (using password: YES)
```

I can connect to MySQL server just like always on the terminal using `mysql -uroot`.

This is the code I have in my project:

```swift
app.databases.use(.mysql(
    hostname: Environment.get("DATABASE_HOST") ?? "127.0.0.1",
    username: Environment.get("DATABASE_USERNAME") ?? "root",
    password: Environment.get("DATABASE_PASSWORD") ?? "",
    database: Environment.get("DATABASE_NAME") ?? "vaportest",
    tlsConfiguration: .forClient(certificateVerification: .none)
), as: .mysql)
```

I guess password should be an optional parameter, I tried with `nil` and `.none` but no luck.

I also tried to connect by `url` but I'm unable to find which is the correct format for a valid MySQL url 😟

**Comment by gwynne** [comment]
Copying the results of my investigation over from #196: The MySQLNIO layer is incorrectly encoding a complete auth response for an empty password "", when the correct behavior for the `mysql_native_password` plugin is to encode no auth response at all in that case. The existing behavior is already correct for the `caching_sha2_password` plugin, which is why this already works with an empty string when using MySQL 8.0. I will be opening a PR against https://github.com/vapor/mysql-nio momentarily to fix this issue.
