### ISSUE TITLE
fix last insert id when uuid/int id types mixed

### ISSUE THREAD

**Issue by tanner0101** [vapor/mysql-driver#39]
Moving https://github.com/vapor/fluent/pull/262 here.

**Comment by cuva** [comment]
@tanner0101 You mentioned on vapor/fluent#259 how values could be truncated on save (and that we shouldn't assume that the `id` passed on the entity is what's been written to the database. Is that specific to SQLLite or could it also be possible in MySQL? If not - it indeed looks life returning `.null` when the `idType` is other than `.int` would work. Otherwise I'm not exactly sure how we'd retrieve the inserted row if its `id` changed 😅.

**Comment by cuva** [comment]
Hum.. right - returning the value from `results` may actually be more appropriate.

**Comment by tanner0101** [comment]
Using the value returned by the DB is definitely better, but unfortunately it appears both MySQL and SQLite only support returning auto-incremented IDs. Luckily I'm also pretty sure they would both throw errors if data gets truncated instead of just silently truncating it. So I think this is a fine solution.

**Comment by cuva** [comment]
Cool - yep that's what I figured! It also has the benefit of avoiding an unnecessary `SELECT LAST_INSERT_ID` after each assertion for `.uuid` entities 👍
